- name: Reserve Next Available IP from Morpheus Pool
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    morpheus_url: MORPHEUS_URL="https://hpepmcmp21.hpe.lab"
    api_token: "871a4bfa-6f96-4043-b7cc-52711171f088"
    network_pool_id: "6"
    
    # Construct the full API endpoint
    api_endpoint: "{{ morpheus_url }}/api/networks/pools/{{ network_pool_id }}/ips"

  tasks:
    - name: API - Reserve the next available IP
      ansible.builtin.uri:
        url: "{{ api_endpoint }}"
        method: POST
        headers:
          Authorization: "Bearer {{ api_token }}"
          Content-Type: "application/json"
        body_format: json
        # By providing an empty string for ipAddress, Morpheus allocates the next available one.
        body: '{"networkPoolIp": {"ipAddress": "","staticIp": true,"hostname": "host-1"}}'
        validate_certs: false # Equivalent to 'curl -k' for self-signed/local certs
        status_code: 200, 201 # Expect either OK (200) or Created (201)
      register: ip_reservation_result
      # Stop the playbook if the reservation fails.
      fail_on_error: true
      
    - name: 2. Extract the reserved IP address
      # Use the 'json_query' filter to parse the response JSON and extract the value.
      ansible.builtin.set_fact:
        reserved_ip: "{{ ip_reservation_result.json | json_query('networkPoolIp.ipAddress') }}"

    - name: 3. Display the reserved IP
      ansible.builtin.debug:
        msg: "✅ Successfully reserved IP address {{ reserved_ip }} from Pool ID {{ network_pool_id }}"
        
    # Example: The reserved IP is now available in the 'reserved_ip' variable 
    # and can be used in subsequent tasks.
    # - name: 4. Example - Use the reserved IP for a new instance
    #   ...
    #   vars:
    #     new_instance_ip: "{{ reserved_ip }}"
