- name: Start service
  hosts: all # here give your instance name
  become: yes
  become_user: root
  tasks:
    - name: Start the service "firewalld"
      service:
        name: firewalld
        state: started
