- name: Stop service
  hosts: localhost # here give your instance name
  become: yes
  become_user: root
  tasks:
    - name: Stop the service "firewalld"
      service:
        name: firewalld
        state: stopped
